name: ezBookkeeping
package: cloud.lazycat.app.ezbookkeeping
version: 1.1.1
min_os_version: 1.3.8
description: 一个自托管 (self-hosted) 的轻量个人账本应用。
homepage: https://github.com/mayswind/ezbookkeeping
author: mayswind
application:
  subdomain: ezbookkeeping
  background_task: true
  public_path:
    - /
  routes:
    - /=http://ezbookkeeping:8080/
services:
  ezbookkeeping:
    # mayswind/ezbookkeeping:1.1.1
    image: registry.lazycat.cloud/czyt/mayswind/ezbookkeeping:c978a658e4a2132f
    environment:
      - EBK_DATABASE_DB_TYPE=sqlite3
      - EBK_DATABASE_DB_PATH=/ezbookkeeping/data/ezbookkeeping.db
      - EBK_SERVER_DOMAIN=${LAZYCAT_APP_DOMAIN}
      - EBK_SERVER_ROOT_URL=https://${LAZYCAT_APP_DOMAIN}
      - EBK_SERVER_ENABLE_GZIP=true
      - EBK_LOG_MODE=file
      - EBK_SECURITY_SECRET_KEY={{stable_secret "palmr#encryption_key" | substr 0 32}}
    binds:
      - /lzcapp/var/data:/ezbookkeeping/data
      - /lzcapp/var/storage:/ezbookkeeping/storage
      - /lzcapp/var/log:/ezbookkeeping/log

    setup_script: |
      chown 1000:1000 /lzcapp/var/data
      chown 1000:1000 /lzcapp/var/storage
      chown 1000:1000 /lzcapp/var/log

locales:
  zh:
    name: "ezBookkeeping"
    description: "一款轻量级、可自托管的个人财务应用程序，具有用户友好的界面和强大的记账功能。"
  en:
    name: "ezBookkeeping"
    description: "A lightweight, self-hosted personal finance app with a user-friendly interface and powerful bookkeeping features."
